name: namada-watchdog 🐶

on:
  schedule:
    - cron: '0 0 * * *'  # Midnight UTC
    - cron: '0 12 * * *' # Noon UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  monitor:
    name: Monitor services
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run status update scripts
        run: |
          python update_status.py
          python update_status_md.py

      - name: Commit and push
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add status_namada.json status_housefire.json STATUS_namada.md STATUS_housefire.md
          if git diff --staged --quiet; then
            echo "No changes detected, skipping commit."
          else
            git commit -m "Automated update: Namada & Housefire service status"
            git push
          fi
